namespace ApiFirstMediatR.Generator.Tests.SourceGenerators;

public class EnumTests : TestBase
{
    [Fact]
    public void ValidAPISpec_WithEnum_GeneratesValidEnum()
    {
        var result = RunGenerators("EnumTests", ApiSpec);
        
        result.Diagnostics.Should().BeEmpty();
        result.GeneratedSources.Should().HaveCount(4)
            .And.ContainEquivalentSyntaxTree("Dtos_Order.g.cs", ExpectedDto)
            .And.ContainEquivalentSyntaxTree("Dtos_OrderStatus.g.cs", ExpectedEnum);
    }
    
    private const string ApiSpec = @"openapi: 3.0.1
info:
  title: HelloWorld API
  version: v1
paths:
  /order:
    get:
      operationId: GetOrder
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
          description: GET Order Response
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        status:
          type: string
          description: Order Status
          example: approved
          enum:
            - placed
            - approved
            - delivered
security: []";

    private const string ExpectedDto = @"// <auto-generated/>
#nullable enable
#pragma warning disable CS8618

namespace EnumTests.Dtos
{
    public class Order 
    {
        [System.Text.Json.Serialization.JsonPropertyName(""id"")]
        public long? Id { get; set; }
            
        [System.Text.Json.Serialization.JsonPropertyName(""status"")]
        public OrderStatus? Status { get; set; }
    }
}

#pragma warning restore CS8618";
    
    private const string ExpectedEnum = @"// <auto-generated/>
#nullable enable
#pragma warning disable CS8618

namespace EnumTests.Dtos
{
    [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumMemberConverter))]
    public enum OrderStatus
    {
        [System.Runtime.Serialization.EnumMember(Value = ""placed"")]
        Placed,
        [System.Runtime.Serialization.EnumMember(Value = ""approved"")]
        Approved,
        [System.Runtime.Serialization.EnumMember(Value = ""delivered"")]
        Delivered
    }
}

#pragma warning restore CS8618";
}